2022-02-24 16:07:04,189 INFO    Thread-208:534558 [wandb_setup.py:_flush():75] Loading settings from /home/sandip/.config/wandb/settings
2022-02-24 16:07:04,189 INFO    Thread-208:534558 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-02-24 16:07:04,189 INFO    Thread-208:534558 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'entity': 'cookie303', 'project': 'Assignment1', 'root_dir': '/home/sandip/Desktop/DL/Assignment 1', 'silent': 'true', 'run_id': 'le4k3sgr', 'sweep_param_path': '/home/sandip/Desktop/DL/Assignment 1/wandb/sweep-fd0c0zla/config-le4k3sgr.yaml', 'sweep_id': 'fd0c0zla'}
2022-02-24 16:07:04,189 INFO    Thread-208:534558 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-24 16:07:04,190 INFO    Thread-208:534558 [wandb_init.py:_log_setup():386] Logging user logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220224_160704-le4k3sgr/logs/debug.log
2022-02-24 16:07:04,190 INFO    Thread-208:534558 [wandb_init.py:_log_setup():387] Logging internal logs to /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220224_160704-le4k3sgr/logs/debug-internal.log
2022-02-24 16:07:04,190 INFO    Thread-208:534558 [wandb_init.py:init():420] calling init triggers
2022-02-24 16:07:04,190 INFO    Thread-208:534558 [wandb_init.py:init():425] wandb.init called with sweep_config: {'activation': 'ReLU', 'batch_size': 64, 'epochs': 5, 'initializer': 'random', 'learning_rate': 0.001, 'num_hidden_neurons': 64, 'num_layers': 3, 'optimizer': 'SGD', 'weight_decay': 0.5}
config: {'epochs': 5, 'num_hidden_layers': 3, 'num_hidden_neurons': 32, 'weight_decay': 0, 'learning_rate': 0.001, 'optimizer': 'SGD', 'batch_size': 16, 'activation': 'Tanh', 'initializer': 'xavier', 'loss': 'CategoricalCrossEntropy'}
2022-02-24 16:07:04,191 INFO    Thread-208:534558 [wandb_init.py:init():471] starting backend
2022-02-24 16:07:04,191 INFO    Thread-208:534558 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-24 16:07:04,192 INFO    Thread-208:534558 [backend.py:ensure_launched():219] starting backend process...
2022-02-24 16:07:04,207 INFO    Thread-208:534558 [backend.py:ensure_launched():224] started backend process with pid: 539057
2022-02-24 16:07:04,210 INFO    Thread-208:534558 [wandb_init.py:init():480] backend started and connected
2022-02-24 16:07:04,223 INFO    Thread-208:534558 [wandb_run.py:_config_callback():966] config_cb None None {'activation': 'ReLU', 'batch_size': 64, 'epochs': 5, 'initializer': 'random', 'learning_rate': 0.001, 'num_hidden_neurons': 64, 'num_layers': 3, 'optimizer': 'SGD', 'weight_decay': 0.5}
2022-02-24 16:07:04,226 INFO    Thread-208:534558 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-24 16:07:04,227 INFO    Thread-208:534558 [wandb_init.py:init():550] updated telemetry
2022-02-24 16:07:04,249 INFO    Thread-208:534558 [wandb_init.py:init():581] communicating current version
2022-02-24 16:07:04,869 INFO    Thread-208:534558 [wandb_init.py:init():586] got version response 
2022-02-24 16:07:04,869 INFO    Thread-208:534558 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-24 16:07:05,194 INFO    Thread-208:534558 [wandb_init.py:init():624] starting run threads in backend
2022-02-24 16:07:09,880 INFO    Thread-208:534558 [wandb_run.py:_console_start():1827] atexit reg
2022-02-24 16:07:09,880 INFO    Thread-208:534558 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-24 16:07:09,881 INFO    Thread-208:534558 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-24 16:07:09,881 INFO    Thread-208:534558 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-24 16:07:09,881 INFO    Thread-208:534558 [wandb_init.py:init():651] run started, returning control to user process
2022-02-24 16:07:11,103 INFO    Thread-208:534558 [wandb_run.py:finish():1468] finishing run cookie303/Assignment1/le4k3sgr
2022-02-24 16:07:11,103 INFO    Thread-208:534558 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 1
2022-02-24 16:07:11,106 INFO    Thread-208:534558 [wandb_run.py:_restore():1769] restore
2022-02-24 16:07:11,389 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 753
}

2022-02-24 16:07:11,738 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 753
}

2022-02-24 16:07:12,222 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 7309
}

2022-02-24 16:07:12,328 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21834
}

2022-02-24 16:07:12,433 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21834
}

2022-02-24 16:07:12,542 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21834
}

2022-02-24 16:07:12,646 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 753
  total_bytes: 21834
}

2022-02-24 16:07:12,750 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:12,856 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:12,960 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,064 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,168 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,272 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,376 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:13,484 INFO    Thread-208:534558 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21834
  total_bytes: 21834
}

2022-02-24 16:07:14,433 INFO    Thread-208:534558 [wandb_run.py:_restore():1769] restore
2022-02-24 16:07:15,796 ERROR   Thread-208:534558 [wandb_run.py:_atexit_cleanup():1815] Problem finishing run
Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 302, in _run_job
    self._function()
  File "/tmp/ipykernel_534558/553927813.py", line 55, in sweep
    model.train(X, y_train_one_hot, validation_data=(X_val, y_val),
  File "/home/sandip/Desktop/DL/Assignment 1/NN/Model.py", line 114, in train
    self.validate(X_val, Y_val)
  File "/home/sandip/Desktop/DL/Assignment 1/NN/Model.py", line 134, in validate
    batch_loss = self.loss.forward(output, batch_Y)
  File "/home/sandip/Desktop/DL/Assignment 1/NN/Loss/CategoricalCrossEntropy.py", line 15, in forward
    return np.sum(log_likelihood * y_true, axis=1)
ValueError: operands could not be broadcast together with shapes (6000,10) (6000,) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1805, in _atexit_cleanup
    self._on_finish()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1988, in _on_finish
    self._poll_exit_response = self._wait_for_finish()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1928, in _wait_for_finish
    poll_exit_resp = self._backend.interface.communicate_poll_exit()
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 586, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 402, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/sandip/anaconda3/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/sandip/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
Exception
