2022-02-25 17:14:31,588 INFO    MainThread:705752 [internal.py:wandb_internal():89] W&B internal server running at pid: 705752, started at: 2022-02-25 17:14:31.588236
2022-02-25 17:14:31,590 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: check_version
2022-02-25 17:14:31,590 DEBUG   SenderThread:705752 [sender.py:send():235] send: header
2022-02-25 17:14:31,590 DEBUG   SenderThread:705752 [sender.py:send_request():249] send_request: check_version
2022-02-25 17:14:31,591 INFO    WriterThread:705752 [datastore.py:open_for_write():77] open: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/run-1pb6m8wg.wandb
2022-02-25 17:14:31,642 DEBUG   SenderThread:705752 [sender.py:send():235] send: run
2022-02-25 17:14:31,951 INFO    SenderThread:705752 [dir_watcher.py:__init__():169] watching files in: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files
2022-02-25 17:14:31,952 INFO    SenderThread:705752 [sender.py:_start_run_threads():809] run started: 1pb6m8wg with start time 1645789470
2022-02-25 17:14:31,952 DEBUG   SenderThread:705752 [sender.py:send():235] send: summary
2022-02-25 17:14:31,954 INFO    SenderThread:705752 [sender.py:_save_file():944] saving file wandb-summary.json with policy end
2022-02-25 17:14:31,955 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: run_start
2022-02-25 17:14:32,952 INFO    Thread-8  :705752 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/wandb-summary.json
2022-02-25 17:14:33,217 DEBUG   HandlerThread:705752 [meta.py:__init__():36] meta init
2022-02-25 17:14:33,217 DEBUG   HandlerThread:705752 [meta.py:__init__():50] meta init done
2022-02-25 17:14:33,217 DEBUG   HandlerThread:705752 [meta.py:probe():210] probe
2022-02-25 17:14:33,218 DEBUG   HandlerThread:705752 [meta.py:_setup_git():200] setup git
2022-02-25 17:14:33,238 DEBUG   HandlerThread:705752 [meta.py:_setup_git():207] setup git done
2022-02-25 17:14:33,238 DEBUG   HandlerThread:705752 [meta.py:_save_pip():54] save pip
2022-02-25 17:14:33,239 DEBUG   HandlerThread:705752 [meta.py:_save_pip():68] save pip done
2022-02-25 17:14:33,239 DEBUG   HandlerThread:705752 [meta.py:_save_conda():75] save conda
2022-02-25 17:14:33,952 INFO    Thread-8  :705752 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/conda-environment.yaml
2022-02-25 17:14:33,952 INFO    Thread-8  :705752 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/requirements.txt
2022-02-25 17:14:36,772 DEBUG   HandlerThread:705752 [meta.py:_save_conda():85] save conda done
2022-02-25 17:14:36,772 DEBUG   HandlerThread:705752 [meta.py:probe():248] probe done
2022-02-25 17:14:36,774 DEBUG   SenderThread:705752 [sender.py:send():235] send: files
2022-02-25 17:14:36,774 INFO    SenderThread:705752 [sender.py:_save_file():944] saving file wandb-metadata.json with policy now
2022-02-25 17:14:36,778 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:14:36,778 DEBUG   SenderThread:705752 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:14:36,954 INFO    Thread-8  :705752 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/conda-environment.yaml
2022-02-25 17:14:36,954 INFO    Thread-8  :705752 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/wandb-metadata.json
2022-02-25 17:14:36,955 INFO    Thread-8  :705752 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/output.log
2022-02-25 17:14:37,742 INFO    Thread-11 :705752 [upload_job.py:push():137] Uploaded file /tmp/tmp35sy68akwandb/2vcanue7-wandb-metadata.json
2022-02-25 17:14:38,955 INFO    Thread-8  :705752 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/output.log
2022-02-25 17:14:46,961 INFO    Thread-8  :705752 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/output.log
2022-02-25 17:14:48,962 INFO    Thread-8  :705752 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/output.log
2022-02-25 17:14:52,059 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:14:52,059 DEBUG   SenderThread:705752 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:14:57,144 WARNING MainThread:705752 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-25 17:15:01,304 DEBUG   SenderThread:705752 [sender.py:send():235] send: stats
2022-02-25 17:15:07,308 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:15:07,308 DEBUG   SenderThread:705752 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:15:22,561 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:15:22,561 DEBUG   SenderThread:705752 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:15:31,360 DEBUG   SenderThread:705752 [sender.py:send():235] send: stats
2022-02-25 17:15:37,814 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:15:37,815 DEBUG   SenderThread:705752 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:15:53,080 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:15:53,081 DEBUG   SenderThread:705752 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:16:01,425 DEBUG   SenderThread:705752 [sender.py:send():235] send: stats
2022-02-25 17:16:08,336 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:16:08,336 DEBUG   SenderThread:705752 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:16:28,336 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:16:42,033 ERROR   SenderThread:705752 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/sandip/anaconda3/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/home/sandip/anaconda3/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/home/sandip/anaconda3/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/sandip/anaconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/sandip/anaconda3/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/sandip/anaconda3/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2022-02-25 17:16:48,337 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:16:56,657 WARNING FileStreamThread:705752 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f408b36e340>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 2, 'content': ['{"system.cpu": 67.8, "system.memory": 61.35, "system.disk": 10.8, "system.proc.memory.availableMB": 6104.79, "system.proc.memory.rssMB": 387.88, "system.proc.memory.percent": 2.46, "system.proc.cpu.threads": 18.0, "system.network.sent": 2157175, "system.network.recv": 11569916, "_wandb": true, "_timestamp": 1645789561, "_runtime": 91}']}}, 'dropped': 0}}
2022-02-25 17:17:07,435 WARNING FileStreamThread:705752 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f408b36e340>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 2, 'content': ['{"system.cpu": 67.8, "system.memory": 61.35, "system.disk": 10.8, "system.proc.memory.availableMB": 6104.79, "system.proc.memory.rssMB": 387.88, "system.proc.memory.percent": 2.46, "system.proc.cpu.threads": 18.0, "system.network.sent": 2157175, "system.network.recv": 11569916, "_wandb": true, "_timestamp": 1645789561, "_runtime": 91}']}}, 'dropped': 0}}
2022-02-25 17:17:07,903 ERROR   SenderThread:705752 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:17:07,904 ERROR   SenderThread:705752 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:17:08,337 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:17:13,700 WARNING FileStreamThread:705752 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f408b36e340>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 2, 'content': ['{"system.cpu": 67.8, "system.memory": 61.35, "system.disk": 10.8, "system.proc.memory.availableMB": 6104.79, "system.proc.memory.rssMB": 387.88, "system.proc.memory.percent": 2.46, "system.proc.cpu.threads": 18.0, "system.network.sent": 2157175, "system.network.recv": 11569916, "_wandb": true, "_timestamp": 1645789561, "_runtime": 91}']}}, 'dropped': 0}}
2022-02-25 17:17:24,161 WARNING FileStreamThread:705752 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f408b36e340>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 2, 'content': ['{"system.cpu": 67.8, "system.memory": 61.35, "system.disk": 10.8, "system.proc.memory.availableMB": 6104.79, "system.proc.memory.rssMB": 387.88, "system.proc.memory.percent": 2.46, "system.proc.cpu.threads": 18.0, "system.network.sent": 2157175, "system.network.recv": 11569916, "_wandb": true, "_timestamp": 1645789561, "_runtime": 91}']}}, 'dropped': 0}}
2022-02-25 17:17:26,802 ERROR   SenderThread:705752 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:17:26,802 ERROR   SenderThread:705752 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:17:28,338 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:17:41,690 WARNING FileStreamThread:705752 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f408b36e340>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 2, 'content': ['{"system.cpu": 67.8, "system.memory": 61.35, "system.disk": 10.8, "system.proc.memory.availableMB": 6104.79, "system.proc.memory.rssMB": 387.88, "system.proc.memory.percent": 2.46, "system.proc.cpu.threads": 18.0, "system.network.sent": 2157175, "system.network.recv": 11569916, "_wandb": true, "_timestamp": 1645789561, "_runtime": 91}']}}, 'dropped': 0}}
2022-02-25 17:17:48,339 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:18:08,340 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:18:28,341 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:18:48,341 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:19:08,342 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:19:21,261 WARNING FileStreamThread:705752 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f408b36e340>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 17:19:28,343 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:19:28,941 ERROR   SenderThread:705752 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:19:28,942 ERROR   SenderThread:705752 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:19:39,616 WARNING FileStreamThread:705752 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f408b36e340>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 17:19:44,233 WARNING FileStreamThread:705752 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f408b36e340>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/1pb6m8wg/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-02-25 17:19:48,343 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:20:08,344 DEBUG   HandlerThread:705752 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:20:24,245 WARNING MainThread:705752 [internal.py:wandb_internal():152] Internal process interrupt: 2
2022-02-25 17:20:24,245 ERROR   MainThread:705752 [internal.py:wandb_internal():155] Internal process interrupted.
2022-02-25 17:20:24,363 INFO    HandlerThread:705752 [handler.py:finish():739] shutting down handler
2022-02-25 17:20:25,087 INFO    WriterThread:705752 [datastore.py:close():281] close: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/run-1pb6m8wg.wandb
2022-02-25 17:21:56,826 INFO    SenderThread:705752 [sender.py:finish():1075] shutting down sender
2022-02-25 17:21:56,826 INFO    SenderThread:705752 [dir_watcher.py:finish():283] shutting down directory watcher
2022-02-25 17:21:57,044 INFO    SenderThread:705752 [dir_watcher.py:finish():313] scan: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files
2022-02-25 17:21:57,044 INFO    SenderThread:705752 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/config.yaml config.yaml
2022-02-25 17:21:57,045 INFO    SenderThread:705752 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/requirements.txt requirements.txt
2022-02-25 17:21:57,045 INFO    SenderThread:705752 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/conda-environment.yaml conda-environment.yaml
2022-02-25 17:21:57,045 INFO    SenderThread:705752 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/output.log output.log
2022-02-25 17:21:57,045 INFO    SenderThread:705752 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/wandb-summary.json wandb-summary.json
2022-02-25 17:21:57,045 INFO    SenderThread:705752 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/wandb-metadata.json wandb-metadata.json
2022-02-25 17:21:57,045 INFO    SenderThread:705752 [file_pusher.py:finish():177] shutting down file pusher
2022-02-25 17:21:57,045 INFO    SenderThread:705752 [file_pusher.py:join():182] waiting for file pusher
2022-02-25 17:21:58,216 INFO    Thread-15 :705752 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/output.log
2022-02-25 17:21:58,274 INFO    Thread-13 :705752 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/requirements.txt
2022-02-25 17:21:58,275 INFO    Thread-12 :705752 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/config.yaml
2022-02-25 17:21:58,330 INFO    Thread-16 :705752 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/wandb-summary.json
2022-02-25 17:21:58,421 INFO    Thread-14 :705752 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171424-1pb6m8wg/files/conda-environment.yaml
2022-02-25 17:21:59,547 INFO    MainThread:705752 [internal.py:handle_exit():79] Internal process exited
